# Generated by Django 3.2 on 2021-04-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('goal', models.TextField(max_length=1000)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_end', models.DateTimeField()),
                ('importance', models.CharField(choices=[(1, 'very importance'), (2, 'importance'), (3, 'it would be better'), (4, 'not very important'), (5, 'trifle')], default=1, max_length=1)),
                ('active', models.BooleanField(default=True)),
                ('completeness', models.BooleanField(default=False)),
            ],
        ),
    ]
