# Generated by Django 3.2 on 2021-04-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_everything', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='importance',
            field=models.CharField(choices=[('1', 'very importance'), ('2', 'importance'), ('3', 'it would be better'), ('4', 'not very important'), ('5', 'trifle')], default='1', max_length=100),
        ),
    ]
