# Generated by Django 3.2 on 2021-06-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_everything', '0002_alter_task_importance'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='my_completeness',
            field=models.BooleanField(default=False),
        ),
    ]
