# Generated by Django 3.2 on 2021-07-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_everything', '0003_task_my_completeness'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=50)),
                ('name_blog', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=2000)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
