# Generated by Django 3.2 on 2021-09-26 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('for_everything', '0005_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='email',
        ),
    ]
